#!/bin/sh
#
# Sets a new secret from stdin

set -eu

trap 'cryptsetup luksClose secret >/dev/null 2>&1' EXIT
trap 'cryptsetup luksClose secret >/dev/null 2>&1' 2

if [ -b /dev/mapper/secret ]; then
	cryptsetup luksClose secret
fi

/lib/systemd/systemd-cryptsetup attach secret /var/secret.enc - tpm2-device=auto
dd if=/dev/zero of=/dev/mapper/secret bs=64K >/dev/null || true
systemd-ask-password -n 'Key to store: ' > /dev/mapper/secret
sync
cryptsetup luksClose secret

printf "\e[1;32m"
cat << EOF
*------------------------------------------------------------*
| All done! You can now retrieve the key with tpm-secret-get |
*------------------------------------------------------------*
EOF
printf "\e[0m"
