#!/bin/sh
#
# Ouputs a secret after introducing the right PIN

set -eu

trap 'cryptsetup luksClose secret >/dev/null 2>&1' EXIT
trap 'cryptsetup luksClose secret >/dev/null 2>&1' 2

umask 077

if [ -t 1 ]; then
	printf "\e[1;31m"
cat << EOF
*---------------------------------------------*
| This is meant to be piped to other programs |
*---------------------------------------------*
EOF
	printf "\e[0m"
	exit 1
fi

if [ -b /dev/mapper/secret ]; then
	cryptsetup luksClose secret
fi

/lib/systemd/systemd-cryptsetup attach secret /var/secret.enc - tpm2-device=auto
cat /dev/mapper/secret
cryptsetup luksClose secret

